version: "3.7"
services:
  logstash:
    image: netsage/pipeline_logstash:latest
    env_file: .env
    # entrypoint: sleep
    # command: "999999"
    external_links:
      - rabbit
    volumes:
      - ./conf-logstash:/usr/share/logstash/pipeline/
      - ./data:/data
      - ./data/cache:/var/lib/grnoc/netsage/
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.dataUpdate.schedule: "@every 24h"
      ofelia.job-exec.dataUpdate.command: "/tmp/docker_init.sh"
  ofelia: ## Scheduler Task
    image: mcuadros/ofelia:v0.3.0
    command: daemon --docker
    depends_on:
      - logstash
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
