version: "3.7"
services:
  # importer:
  #   image: netsage/pipeline_importer:latest
  #   build:
  #     context: .
  #     dockerfile: compose/importer/Dockerfile
  logstash:
    image: netsage/pipeline_logstash:latest
    build:
      context: .
      dockerfile: ./compose/logstash/Dockerfile
  rabbit:
    image: netsage/rabbitmq:3-management
    build:
      context: .
      dockerfile: ./compose/rabbit/Dockerfile
