version: "3.7"
services:
  netflow_collector:
    image: pmacct/nfacctd:v1.7.5
    # command: sleep 99999
    # restart: on-failure
    depends_on:
      - rabbit
    ports:
      - "9996:9996/udp"
    volumes:
      - ./conf/netflow/nfacctd.conf:/etc/pmacct/nfacctd.conf
      - ./conf/netflow/pretag.map:/etc/pmacct/pretag.map
      - ./conf/netflow/ipfix.primitives.lst:/etc/pmacct/ipfix.primitives.lst
  sflow_collector:
    image: pmacct/sfacctd:v1.7.5
    # command: sleep 99999
    # restart: on-failure
    depends_on:
      - rabbit
    ports:
      - "9997:9997/udp"
    volumes:
      - ./conf/sflow/sfacctd.conf:/etc/pmacct/sfacctd.conf
      - ./conf/sflow/pretag.map:/etc/pmacct/pretag.map
      - ./conf/sflow/ipfix.primitives.lst:/etc/pmacct/ipfix.primitives.lst
  rabbit:
    image: netsage/rabbitmq:3-management
    env_file: .env
    volumes:
      - ./data/rabbit:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"
